# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d0433ef1f4c6b44f6e70b8c99d0d5a7e599f3bc7f774885d5ed066f79842bd89a68b487bd84f54aeb231dc83da35ede248bd7ed057c0edd5dd123946a2ea872

test:
  secret_key_base: bf7a91d7e69cd8a75cb6f9d008a8b10d6c5366533a580044dc5533b19a31b110e4483430690f867a28ac8be264ed4f2a4d5654ba3e471c419b141b842f16308a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
